import socket


IPAddr = socket.gethostbyname(socket.gethostname())

JORDAN_API_PORT = 5000
JORDAN_API_PROTOCOL = 'http'
JORDAN_API_PATH_PREFIX = '/jordan'
JORDAN_API_URL_PREFIX = f"{JORDAN_API_PROTOCOL}://{IPAddr}:{JORDAN_API_PORT}{JORDAN_API_PATH_PREFIX}"

JORDAN_OPEN_API_DOC_SUFFIX = JORDAN_API_PATH_PREFIX + '/swagger-ui'
JORDAN_OPEN_API_URL = f"{JORDAN_API_PROTOCOL}://{IPAddr}:{JORDAN_API_PORT}{JORDAN_OPEN_API_DOC_SUFFIX}"
